# Confluence MCP Server
# Atlassian Confluence integration for documentation and knowledge management

apiVersion: gostoa.dev/v1
kind: MCPServer
metadata:
  name: confluence
  tenant: _platform
  version: "1.0.0"
  labels:
    managed-by: gitops
    environment: prod

spec:
  displayName: Confluence
  description: |
    Atlassian Confluence integration for AI-powered documentation access.
    Search, read, and manage Confluence spaces and pages.
  icon: https://cdn.worldvectorlogo.com/logos/confluence-1.svg
  category: public
  status: active
  documentationUrl: https://developer.atlassian.com/cloud/confluence/rest/v2/intro/

  visibility:
    public: true

  subscription:
    requiresApproval: true
    autoApproveRoles:
      - cpi-admin
    defaultPlan: free

  tools:
    - name: search-content
      displayName: Search Content
      description: Search for content across Confluence spaces using CQL
      endpoint: /wiki/rest/api/content/search
      method: GET
      enabled: true
      inputSchema:
        type: object
        properties:
          cql:
            type: string
            description: Confluence Query Language (CQL) query string
          limit:
            type: integer
            description: Maximum number of results
            default: 25
          start:
            type: integer
            description: Starting index for pagination
            default: 0
        required:
          - cql
      timeout: 30s
      rateLimit:
        requestsPerMinute: 100

    - name: get-page
      displayName: Get Page
      description: Retrieve a Confluence page by ID with its content
      endpoint: /wiki/rest/api/content/{page_id}
      method: GET
      enabled: true
      inputSchema:
        type: object
        properties:
          page_id:
            type: string
            description: The Confluence page ID
          expand:
            type: string
            description: Properties to expand (body.storage, version, space)
            default: "body.storage,version,space"
        required:
          - page_id
      timeout: 30s
      rateLimit:
        requestsPerMinute: 100

    - name: list-spaces
      displayName: List Spaces
      description: List all Confluence spaces the user has access to
      endpoint: /wiki/rest/api/space
      method: GET
      enabled: true
      inputSchema:
        type: object
        properties:
          limit:
            type: integer
            description: Maximum number of results
            default: 25
          type:
            type: string
            description: Filter by space type (global, personal)
        required: []
      timeout: 30s
      rateLimit:
        requestsPerMinute: 60

    - name: get-space-content
      displayName: Get Space Content
      description: List all pages in a Confluence space
      endpoint: /wiki/rest/api/space/{space_key}/content
      method: GET
      enabled: true
      inputSchema:
        type: object
        properties:
          space_key:
            type: string
            description: The space key (e.g., "DOCS", "TEAM")
          depth:
            type: string
            description: Depth of content tree to return (all, root)
            default: "all"
          limit:
            type: integer
            description: Maximum number of results
            default: 25
        required:
          - space_key
      timeout: 30s
      rateLimit:
        requestsPerMinute: 60

    - name: create-page
      displayName: Create Page
      description: Create a new Confluence page
      endpoint: /wiki/rest/api/content
      method: POST
      enabled: true
      requiresApproval: true
      inputSchema:
        type: object
        properties:
          space_key:
            type: string
            description: The space key where the page will be created
          title:
            type: string
            description: Page title
          body:
            type: string
            description: Page content in storage format (XHTML)
          parent_id:
            type: string
            description: Parent page ID (optional)
        required:
          - space_key
          - title
          - body
      timeout: 60s
      rateLimit:
        requestsPerMinute: 20

    - name: update-page
      displayName: Update Page
      description: Update an existing Confluence page
      endpoint: /wiki/rest/api/content/{page_id}
      method: PUT
      enabled: true
      requiresApproval: true
      inputSchema:
        type: object
        properties:
          page_id:
            type: string
            description: The page ID to update
          title:
            type: string
            description: New page title
          body:
            type: string
            description: New page content in storage format
          version_number:
            type: integer
            description: Current version number (for optimistic locking)
        required:
          - page_id
          - title
          - body
          - version_number
      timeout: 60s
      rateLimit:
        requestsPerMinute: 20

  backend:
    baseUrl: ${CONFLUENCE_BASE_URL:https://your-domain.atlassian.net}
    auth:
      type: api-key
      secretRef: vault:secret/data/integrations/confluence#api_token
    timeout: 30s
    retries: 3
