apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-dev
resources:
  - ../../base
  - gateway-instances.yaml
  - ingress.yaml
patches:
  - target:
      kind: Deployment
      name: stoa-gateway
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_ENVIRONMENT
          value: "dev"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_INSTANCE_NAME
          value: "stoa-gateway-dev"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_GATEWAY_EXTERNAL_URL
          value: "https://dev-gw-k3s.gostoa.dev"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_GATEWAY_PUBLIC_URL
          value: "https://dev-gw-k3s.gostoa.dev"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_DEPLOYMENT_MODE
          value: "edge"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_TARGET_GATEWAY_TYPE
          value: "stoa"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_TOPOLOGY
          value: "native-edge"
  - target:
      kind: Deployment
      name: stoa-link-wm
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: stoa-link-wm
      spec:
        template:
          spec:
            containers:
              - name: stoa-gateway
                env:
                  - name: STOA_ENVIRONMENT
                    value: "dev"
                  - name: STOA_INSTANCE_NAME
                    value: "stoa-link-wm-dev"
                  - name: STOA_GATEWAY_EXTERNAL_URL
                    value: "https://dev-wm-k3s.gostoa.dev"
                  - name: STOA_GATEWAY_PUBLIC_URL
                    value: "https://dev-wm-k3s.gostoa.dev"
                  - name: STOA_TARGET_GATEWAY_URL
                    value: "https://dev-wm.gostoa.dev"
                  - name: STOA_GATEWAY_UI_URL
                    value: "https://dev-wm-ui.gostoa.dev"
                  - name: STOA_DEPLOYMENT_MODE
                    value: "connect"
                  - name: STOA_TARGET_GATEWAY_TYPE
                    value: "webmethods"
                  - name: STOA_TOPOLOGY
                    value: "remote-agent"
