#!/usr/bin/env node
/**
 * E2E Audit Report Generator
 *
 * Parses Playwright JSON results and generates a markdown audit report
 * with summary, failed tests, coverage by feature, and correction plan template.
 *
 * Usage:
 *   node scripts/generate-audit.js
 *
 * Expects: reports/results.json (Playwright JSON reporter output)
 * Outputs: reports/audit-report.md
 */

const fs = require('fs');
const path = require('path');

const RESULTS_PATH = path.join(__dirname, '..', 'reports', 'results.json');
const OUTPUT_PATH = path.join(__dirname, '..', 'reports', 'audit-report.md');

function main() {
  // Ensure reports directory exists
  const reportsDir = path.dirname(OUTPUT_PATH);
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  if (!fs.existsSync(RESULTS_PATH)) {
    const fallback = [
      '# E2E Audit Report',
      '',
      `**Date**: ${new Date().toISOString().split('T')[0]}`,
      '',
      '## Status: No Results',
      '',
      'No `reports/results.json` found. Tests may not have run.',
      '',
    ].join('\n');
    fs.writeFileSync(OUTPUT_PATH, fallback);
    console.log('No results.json found — wrote fallback report.');
    return;
  }

  const results = JSON.parse(fs.readFileSync(RESULTS_PATH, 'utf-8'));
  const stats = results.stats || {};

  const total = (stats.expected || 0) + (stats.unexpected || 0) + (stats.flaky || 0) + (stats.skipped || 0);
  const passed = stats.expected || 0;
  const failed = stats.unexpected || 0;
  const flaky = stats.flaky || 0;
  const skipped = stats.skipped || 0;
  const duration = stats.duration ? (stats.duration / 1000).toFixed(1) : '?';
  const passRate = total > 0 ? ((passed / total) * 100).toFixed(1) : '0.0';

  // Collect failed tests
  const failedTests = [];
  const featureCoverage = {};

  for (const suite of results.suites || []) {
    collectResults(suite, failedTests, featureCoverage);
  }

  // Build report
  const lines = [];
  const date = new Date().toISOString().split('T')[0];

  lines.push('# E2E Audit Report');
  lines.push('');
  lines.push(`**Date**: ${date}`);
  lines.push(`**Duration**: ${duration}s`);
  lines.push(`**Pass Rate**: ${passRate}%`);
  lines.push('');

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Count |');
  lines.push('|--------|-------|');
  lines.push(`| Total | ${total} |`);
  lines.push(`| Passed | ${passed} |`);
  lines.push(`| Failed | ${failed} |`);
  lines.push(`| Flaky | ${flaky} |`);
  lines.push(`| Skipped | ${skipped} |`);
  lines.push('');

  // Failed tests
  if (failedTests.length > 0) {
    lines.push('## Failed Tests');
    lines.push('');
    for (const t of failedTests) {
      lines.push(`### ${t.title}`);
      lines.push(`- **File**: ${t.file}`);
      lines.push(`- **Project**: ${t.project}`);
      if (t.error) {
        lines.push(`- **Error**: \`${t.error.substring(0, 200)}\``);
      }
      lines.push('');
    }
  } else {
    lines.push('## Failed Tests');
    lines.push('');
    lines.push('None — all tests passed.');
    lines.push('');
  }

  // Coverage by feature
  lines.push('## Coverage by Feature');
  lines.push('');
  lines.push('| Feature | Total | Passed | Failed | Pass Rate |');
  lines.push('|---------|-------|--------|--------|-----------|');

  for (const [feature, counts] of Object.entries(featureCoverage)) {
    const fTotal = counts.passed + counts.failed;
    const fRate = fTotal > 0 ? ((counts.passed / fTotal) * 100).toFixed(0) : '0';
    lines.push(`| ${feature} | ${fTotal} | ${counts.passed} | ${counts.failed} | ${fRate}% |`);
  }
  lines.push('');

  // Correction plan template
  lines.push('## Correction Plan');
  lines.push('');
  lines.push('| # | Failed Test | Root Cause | Fix | Priority | Assignee |');
  lines.push('|---|-------------|------------|-----|----------|----------|');
  if (failedTests.length > 0) {
    failedTests.forEach((t, i) => {
      lines.push(`| ${i + 1} | ${t.title} | _TBD_ | _TBD_ | _TBD_ | _TBD_ |`);
    });
  } else {
    lines.push('| - | No failures | - | - | - | - |');
  }
  lines.push('');

  lines.push('---');
  lines.push(`*Generated by \`e2e/scripts/generate-audit.js\` on ${date}*`);

  const report = lines.join('\n');
  fs.writeFileSync(OUTPUT_PATH, report);
  console.log(`Audit report written to ${OUTPUT_PATH}`);
  console.log(`  Total: ${total}, Passed: ${passed}, Failed: ${failed}, Flaky: ${flaky}`);
}

function collectResults(suite, failedTests, featureCoverage) {
  // Determine feature name from suite file path
  const file = suite.file || '';
  const featureName = path.basename(file, '.feature') || path.basename(file) || 'unknown';

  if (!featureCoverage[featureName]) {
    featureCoverage[featureName] = { passed: 0, failed: 0 };
  }

  for (const spec of suite.specs || []) {
    for (const test of spec.tests || []) {
      const status = test.status || test.expectedStatus;
      if (status === 'expected' || status === 'passed') {
        featureCoverage[featureName].passed++;
      } else if (status === 'unexpected' || status === 'failed') {
        featureCoverage[featureName].failed++;
        const errorMessage = test.results?.[0]?.error?.message || '';
        failedTests.push({
          title: spec.title || 'Unknown test',
          file: file,
          project: test.projectName || '',
          error: errorMessage,
        });
      }
    }
  }

  // Recurse into child suites
  for (const child of suite.suites || []) {
    collectResults(child, failedTests, featureCoverage);
  }
}

main();
