# These are supported funding model platforms

# GitHub Sponsors
# github: [your-github-username]

# Open Collective
# open_collective: stoa

# Patreon
# patreon: your-patreon

# Ko-fi
# ko_fi: your-kofi

# Custom URL
# custom: https://your-donation-link.com
