/**
 * Contract Tests — Portal ↔ Control Plane API
 *
 * Validates that Portal TypeScript interfaces match the OpenAPI schema
 * generated by the backend. Catches schema drift before it reaches production.
 */
import { describe, expect, it } from 'vitest';
import schema from '../../../control-plane-api/openapi-snapshot.json';

type OpenAPISchema = {
  components: {
    schemas: Record<
      string,
      {
        properties?: Record<string, unknown>;
        required?: string[];
      }
    >;
  };
};

const typedSchema = schema as unknown as OpenAPISchema;

function getSchemaProperties(schemaName: string): string[] {
  const s = typedSchema.components.schemas[schemaName];
  if (!s) throw new Error(`Schema '${schemaName}' not found in OpenAPI snapshot`);
  return Object.keys(s.properties || {});
}

function getRequiredProperties(schemaName: string): string[] {
  const s = typedSchema.components.schemas[schemaName];
  if (!s) throw new Error(`Schema '${schemaName}' not found in OpenAPI snapshot`);
  return s.required || [];
}

/**
 * Portal TS interfaces mapped to their OpenAPI schema counterparts.
 * Properties listed are what the Portal TS type declares.
 */
const PORTAL_TYPE_MAPPINGS: Record<string, string[]> = {
  // MCPSubscriptionResponse → MCPSubscription
  MCPSubscriptionResponse: [
    'id',
    'server_id',
    'tenant_id',
    'status',
    'plan',
    'created_at',
    'expires_at',
    'api_key_prefix',
    'last_rotated_at',
    'rotation_count',
    'has_active_grace_period',
  ],

  // MCPServerResponse → MCPServer
  MCPServerResponse: [
    'id',
    'name',
    'display_name',
    'description',
    'category',
    'status',
    'created_at',
    'updated_at',
  ],

  // ContractResponse → Contract
  ContractResponse: ['id', 'tenant_id', 'name', 'version', 'status', 'created_at', 'updated_at'],

  // PortalAPIResponse → API (portal catalog)
  PortalAPIResponse: [
    'id',
    'name',
    'display_name',
    'version',
    'description',
    'tenant_id',
    'status',
  ],

  // SubscriptionResponse → APISubscription (portal subscriptions)
  SubscriptionResponse: [
    'id',
    'application_id',
    'api_id',
    'api_name',
    'tenant_id',
    'status',
    'api_key_prefix',
    'created_at',
  ],
};

describe('OpenAPI Contract — Portal', () => {
  it('should have a valid OpenAPI snapshot', () => {
    expect(typedSchema.components).toBeDefined();
    expect(typedSchema.components.schemas).toBeDefined();
    expect(Object.keys(typedSchema.components.schemas).length).toBeGreaterThan(50);
  });

  describe.each(Object.entries(PORTAL_TYPE_MAPPINGS))('Schema %s', (schemaName, tsProperties) => {
    it(`should exist in OpenAPI snapshot`, () => {
      const props = getSchemaProperties(schemaName);
      expect(props.length).toBeGreaterThan(0);
    });

    it(`should have all TS-declared properties in OpenAPI`, () => {
      const apiProps = getSchemaProperties(schemaName);
      const missing = tsProperties.filter((p) => !apiProps.includes(p));
      expect(missing).toEqual([]);
    });

    it(`should have required properties covered by TS type`, () => {
      const required = getRequiredProperties(schemaName);
      const covered = tsProperties.filter((p) => required.includes(p));
      expect(covered.length).toBeGreaterThanOrEqual(Math.min(required.length, 3));
    });
  });

  it('should not have unexpected schema removals', () => {
    const expectedSchemas = [
      'MCPSubscriptionResponse',
      'MCPServerResponse',
      'ContractResponse',
      'PortalAPIResponse',
      'SubscriptionResponse',
      'WebhookResponse',
      'UsageSummary',
    ];

    for (const name of expectedSchemas) {
      expect(typedSchema.components.schemas[name]).toBeDefined();
    }
  });
});
