apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stoa-operator
  namespace: stoa-system
  labels:
    prometheus: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: stoa-operator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - stoa-system
