#!/bin/bash
# =============================================================================
# Convert Grafana Dashboard JSONs to K8s ConfigMap YAMLs
# =============================================================================
# CAB-1687: Migration script for GitOps observability
#
# Usage:
#   ./convert-dashboards.sh [--dry-run] [--specific dashboard-name]
#
# Converts docker/observability/grafana/dashboards/*.json
# into k8s/observability/dashboards/<name>-cm.yaml ConfigMaps
# with grafana_dashboard: "1" label for sidecar auto-discovery.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
DASHBOARDS_DIR="${REPO_ROOT}/docker/observability/grafana/dashboards"
OUTPUT_DIR="${REPO_ROOT}/k8s/observability/dashboards"
DRY_RUN=false
SPECIFIC=""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run) DRY_RUN=true; shift ;;
    --specific) SPECIFIC="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [--dry-run] [--specific dashboard-name]"
      echo "  --dry-run    Show what would be created without writing files"
      echo "  --specific   Convert only this dashboard (without .json extension)"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

mkdir -p "${OUTPUT_DIR}"

convert_dashboard() {
  local json_file="$1"
  local name
  name=$(basename "$json_file" .json)
  local cm_name="stoa-dashboard-${name}"
  local output_file="${OUTPUT_DIR}/${name}-cm.yaml"

  # Determine Grafana folder from dashboard tags
  local folder="STOA"
  if jq -e '.tags | index("gateway")' "$json_file" > /dev/null 2>&1; then
    folder="STOA Gateway"
  elif jq -e '.tags | index("tenant")' "$json_file" > /dev/null 2>&1; then
    folder="STOA Tenants"
  elif jq -e '.tags | index("arena")' "$json_file" > /dev/null 2>&1; then
    folder="STOA Arena"
  elif jq -e '.tags | index("security")' "$json_file" > /dev/null 2>&1; then
    folder="STOA Security"
  elif jq -e '.tags | index("ai-factory")' "$json_file" > /dev/null 2>&1; then
    folder="STOA AI Factory"
  fi

  if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${YELLOW}[DRY-RUN]${NC} Would create: ${output_file} (folder: ${folder})"
    return 0
  fi

  # Generate ConfigMap YAML with inline JSON
  cat > "${output_file}" <<EOF
# Auto-generated by convert-dashboards.sh — do not edit manually
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${cm_name}
  namespace: stoa-monitoring
  labels:
    app.kubernetes.io/part-of: stoa-platform
    app.kubernetes.io/component: observability
    grafana_dashboard: "1"
  annotations:
    grafana_folder: "${folder}"
data:
  ${name}.json: |
EOF

  # Indent JSON content by 4 spaces for YAML multiline string
  sed 's/^/    /' "$json_file" >> "${output_file}"

  echo -e "${GREEN}[OK]${NC} ${output_file} (folder: ${folder})"
}

echo -e "${BLUE}STOA Dashboard → ConfigMap Converter${NC}"
echo ""

count=0
if [[ -n "$SPECIFIC" ]]; then
  json_file="${DASHBOARDS_DIR}/${SPECIFIC}.json"
  if [[ -f "$json_file" ]]; then
    convert_dashboard "$json_file"
    count=1
  else
    echo "Dashboard not found: ${json_file}"
    exit 1
  fi
else
  for json_file in "${DASHBOARDS_DIR}"/*.json; do
    [[ -f "$json_file" ]] || continue
    convert_dashboard "$json_file"
    count=$((count + 1))
  done
fi

echo ""
echo -e "${GREEN}Converted ${count} dashboards${NC}"
if [[ "$DRY_RUN" == "true" ]]; then
  echo "(dry-run mode — no files were written)"
fi
