# Tenant Template
# Multi-tenant organization configuration
# Variables are resolved using ${VAR} or ${VAR:default} syntax

apiVersion: apim.cab-i.com/v1
kind: Tenant
metadata:
  name: ${TENANT_ID}
  labels:
    environment: ${ENVIRONMENT}
    managed-by: gitops

spec:
  displayName: ${TENANT_DISPLAY_NAME:${TENANT_ID}}
  description: ${TENANT_DESCRIPTION:}
  status: ${TENANT_STATUS:active}

  # Organization details
  organization:
    name: ${ORG_NAME:}
    domain: ${ORG_DOMAIN:}
    contact:
      name: ${CONTACT_NAME:}
      email: ${CONTACT_EMAIL:}
      phone: ${CONTACT_PHONE:}

  # Tenant quotas and limits
  quotas:
    maxApis: ${MAX_APIS:100}
    maxApplications: ${MAX_APPLICATIONS:50}
    maxUsersPerRole: ${MAX_USERS_PER_ROLE:20}
    maxRequestsPerDay: ${MAX_REQUESTS_PER_DAY:1000000}

  # Available environments for this tenant
  environments:
    - dev
    - staging
    # prod requires explicit enablement
    # - prod

  # RBAC configuration
  roles:
    - name: tenant-admin
      description: Full access to tenant resources
      permissions:
        - apis:*
        - applications:*
        - deployments:*
        - users:*
    - name: devops
      description: Deploy and manage API lifecycle
      permissions:
        - apis:read
        - apis:deploy
        - deployments:*
    - name: developer
      description: Create and manage APIs
      permissions:
        - apis:create
        - apis:read
        - apis:update
        - applications:read
    - name: viewer
      description: Read-only access
      permissions:
        - apis:read
        - applications:read
        - deployments:read

  # Keycloak group mapping
  keycloak:
    groupPrefix: /tenants/${TENANT_ID}
    roles:
      tenant-admin: tenant-admin
      devops: devops
      developer: developer
      viewer: viewer

  # Notification settings
  notifications:
    email:
      enabled: ${EMAIL_NOTIFICATIONS:true}
      recipients:
        - ${CONTACT_EMAIL}
    slack:
      enabled: ${SLACK_NOTIFICATIONS:false}
      webhook: vault:secret/data/${TENANT_ID}/notifications#slack_webhook

  # Audit settings
  audit:
    enabled: true
    retentionDays: ${AUDIT_RETENTION_DAYS:90}

  # Metadata
  metadata:
    createdAt: ${CREATED_AT:}
    createdBy: ${CREATED_BY:}
