# STOA Platform MCP Server
# Native MCP interface for STOA platform management

apiVersion: gostoa.dev/v1
kind: MCPServer
metadata:
  name: stoa-platform
  tenant: _platform
  version: "1.0.0"
  labels:
    managed-by: gitops
    environment: prod

spec:
  displayName: STOA Platform API
  description: |
    Native MCP interface for STOA platform management.
    Provides tools for managing tenants, APIs, deployments, and platform configuration.
  icon: https://portal.gostoa.dev/stoa-icon.svg
  category: platform
  status: active
  documentationUrl: https://docs.gostoa.dev/mcp/stoa-platform

  visibility:
    public: true

  subscription:
    requiresApproval: false
    autoApproveRoles:
      - cpi-admin
      - tenant-admin
    defaultPlan: free

  tools:
    - name: list-tenants
      displayName: List Tenants
      description: List all tenants the authenticated user has access to
      endpoint: /v1/tenants
      method: GET
      enabled: true
      inputSchema:
        type: object
        properties: {}
        required: []
      timeout: 30s
      rateLimit:
        requestsPerMinute: 60

    - name: get-tenant
      displayName: Get Tenant Details
      description: Get detailed information about a specific tenant
      endpoint: /v1/tenants/{tenant_id}
      method: GET
      enabled: true
      inputSchema:
        type: object
        properties:
          tenant_id:
            type: string
            description: The tenant ID
        required:
          - tenant_id
      timeout: 30s
      rateLimit:
        requestsPerMinute: 60

    - name: list-apis
      displayName: List APIs
      description: List all APIs for a specific tenant
      endpoint: /v1/tenants/{tenant_id}/apis
      method: GET
      enabled: true
      inputSchema:
        type: object
        properties:
          tenant_id:
            type: string
            description: The tenant ID
        required:
          - tenant_id
      timeout: 30s
      rateLimit:
        requestsPerMinute: 60

    - name: get-api
      displayName: Get API Details
      description: Get detailed information about a specific API
      endpoint: /v1/tenants/{tenant_id}/apis/{api_name}
      method: GET
      enabled: true
      inputSchema:
        type: object
        properties:
          tenant_id:
            type: string
            description: The tenant ID
          api_name:
            type: string
            description: The API name
        required:
          - tenant_id
          - api_name
      timeout: 30s
      rateLimit:
        requestsPerMinute: 60

    - name: create-api
      displayName: Create API
      description: Create a new API in a tenant
      endpoint: /v1/tenants/{tenant_id}/apis
      method: POST
      enabled: true
      requiresApproval: false
      inputSchema:
        type: object
        properties:
          tenant_id:
            type: string
            description: The tenant ID
          name:
            type: string
            description: API name (lowercase, alphanumeric, hyphens)
          display_name:
            type: string
            description: Human-readable display name
          description:
            type: string
            description: API description
          backend_url:
            type: string
            description: Backend service URL
          version:
            type: string
            description: API version
            default: "1.0.0"
        required:
          - tenant_id
          - name
          - display_name
          - backend_url
      timeout: 60s
      rateLimit:
        requestsPerMinute: 10

    - name: deploy-api
      displayName: Deploy API
      description: Deploy an API to a specific environment
      endpoint: /v1/tenants/{tenant_id}/apis/{api_name}/deploy
      method: POST
      enabled: true
      requiresApproval: true
      inputSchema:
        type: object
        properties:
          tenant_id:
            type: string
            description: The tenant ID
          api_name:
            type: string
            description: The API name
          environment:
            type: string
            description: Target environment (dev, staging, prod)
            enum:
              - dev
              - staging
              - prod
        required:
          - tenant_id
          - api_name
          - environment
      timeout: 120s
      rateLimit:
        requestsPerMinute: 5

    - name: list-subscriptions
      displayName: List Subscriptions
      description: List API subscriptions for a tenant
      endpoint: /v1/tenants/{tenant_id}/subscriptions
      method: GET
      enabled: true
      inputSchema:
        type: object
        properties:
          tenant_id:
            type: string
            description: The tenant ID
        required:
          - tenant_id
      timeout: 30s
      rateLimit:
        requestsPerMinute: 60

  backend:
    baseUrl: https://api.gostoa.dev
    auth:
      type: oauth2
    timeout: 30s
    retries: 3
