apiVersion: stoa.io/v1
kind: WebMethodsAPI
metadata:
  name: crm-api
  version: "1.0.0"
  description: "API CRM pour gestion des contacts et opportunités"
  tags:
    - crm
    - contacts
    - sales

spec:
  type: REST
  basePath: /api/crm/v1
  
  # Backend routing (résolu via aliases/{env}.yaml)
  backend:
    alias: crm-backend
    pathPrefix: /api
    
  # Policies appliquées (ordre d'exécution)
  policies:
    - jwt-validation
    - rate-limit-standard
    - logging-standard
    
  # Configuration authentification
  auth:
    type: oauth2
    required: true
    scopes:
      - crm:read
      - crm:write
      
  # Applications autorisées (vide = toutes les apps enregistrées)
  applications: []
  
  # CORS configuration
  cors:
    enabled: true
    allowOrigins:
      - "https://console.stoa.cab-i.com"
      - "https://portal.stoa.cab-i.com"
    allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
    allowHeaders:
      - Authorization
      - Content-Type
      - X-Request-ID
  
  # Ressources/Endpoints exposés
  resources:
    - path: /contacts
      methods: [GET, POST]
      description: "Liste et création de contacts"
      
    - path: /contacts/{id}
      methods: [GET, PUT, DELETE]
      description: "CRUD sur un contact spécifique"
      
    - path: /contacts/{id}/opportunities
      methods: [GET, POST]
      description: "Opportunités liées à un contact"
      
    - path: /opportunities
      methods: [GET, POST]
      description: "Liste et création d'opportunités"
      
    - path: /opportunities/{id}
      methods: [GET, PUT, DELETE]
      description: "CRUD sur une opportunité spécifique"
