apiVersion: v1
kind: Service
metadata:
  name: stoa-sidecar-kong
spec:
  selector:
    app: stoa-sidecar-kong
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 9191
      targetPort: 9191
      name: metrics
