apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-rec
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: stoa-gateway
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_ENVIRONMENT
          value: "rec"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_INSTANCE_NAME
          value: "stoa-gateway-rec"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_GATEWAY_EXTERNAL_URL
          value: "https://rec-gw.gostoa.dev"
  - target:
      kind: Deployment
      name: stoa-sidecar-kong
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_ENVIRONMENT
          value: "rec"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_INSTANCE_NAME
          value: "STOA Link — Kong (rec)"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_GATEWAY_EXTERNAL_URL
          value: "https://rec-kong.gostoa.dev"
  - target:
      kind: Deployment
      name: stoa-sidecar-webmethods
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_ENVIRONMENT
          value: "rec"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_INSTANCE_NAME
          value: "STOA Link — webMethods (rec)"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_GATEWAY_EXTERNAL_URL
          value: "https://rec-wm.gostoa.dev"
