"""
OpenAPI Contract Tests — structural validation for API schema stability.

Ensures the OpenAPI schema generated by FastAPI matches the committed snapshot
at a structural level (paths, schemas, properties, methods). Tolerant of
Pydantic version differences (allOf/$ref, additionalProperties, title).

When the API changes intentionally, update the snapshot:

    cd control-plane-api && python -c "
    import os, json
    os.environ['ENABLE_DEPLOYMENT_WORKER'] = 'false'
    os.environ['ENABLE_SNAPSHOT_CONSUMER'] = 'false'
    from src.main import app
    with open('openapi-snapshot.json', 'w') as f:
        json.dump(app.openapi(), f, indent=2, sort_keys=True, default=str)
    "
"""

import json
from pathlib import Path

import pytest

from src.config import settings
from src.main import app

SNAPSHOT_PATH = Path(__file__).parent.parent / "openapi-snapshot.json"

REQUIRED_PATHS = [
    "/v1/tenants",
    "/v1/subscriptions",
    "/v1/admin/gateways",
    "/v1/mcp/servers",
    "/health",
    # CAB-1671: expanded contract coverage for 10 critical routers
    "/v1/consumers",
    "/v1/tenants/{tenant_id}/contracts",
    "/v1/portal",
    "/v1/platform",
]

# CAB-1671: Core response schemas that MUST exist in the OpenAPI spec.
# Any removal is a breaking change.
REQUIRED_SCHEMAS = [
    "TenantResponse",
    "SubscriptionResponse",
    "ContractResponse",
    "GatewayInstanceResponse",
    "MCPServerResponse",
    "PlatformStatusResponse",
    # Phase 1 additions
    "APIResponse",
    "ConsumerResponse",
    "DeploymentResponse",
    "ConsumerListResponse",
    "DeploymentListResponse",
]

# CAB-1671: Required fields per schema — catches silent field removals.
REQUIRED_FIELDS = {
    "TenantResponse": ["id", "name", "status"],
    "SubscriptionResponse": ["id", "status", "api_id"],
    "ContractResponse": ["id", "name", "status", "tenant_id"],
    "GatewayInstanceResponse": ["id", "name", "gateway_type", "status"],
    "PlatformStatusResponse": ["gitops", "timestamp"],
    "APIResponse": ["id", "name", "tenant_id"],
    "ConsumerResponse": ["id", "name", "tenant_id", "status"],
    "DeploymentResponse": ["id", "tenant_id", "status"],
}


class TestOpenAPIContract:
    def _get_live_schema(self) -> dict:
        schema = app.openapi()
        return json.loads(json.dumps(schema, sort_keys=True, default=str))

    @pytest.mark.skip(
        reason="CI ghost drift: passes locally, fails in CI due to env-dependent route loading. CAB-2055 follow-up."
    )
    def test_openapi_paths_match_snapshot(self):
        """API paths must match committed snapshot (catches added/removed endpoints)."""
        assert SNAPSHOT_PATH.exists(), (
            f"OpenAPI snapshot not found at {SNAPSHOT_PATH}. "
            "Run the snapshot generation command in the module docstring."
        )

        with open(SNAPSHOT_PATH) as f:
            snapshot = json.load(f)

        live = self._get_live_schema()

        snapshot_paths = set(snapshot.get("paths", {}).keys())
        live_paths = set(live.get("paths", {}).keys())

        added = live_paths - snapshot_paths
        removed = snapshot_paths - live_paths

        assert not added and not removed, (
            f"API paths changed. Update the snapshot.\n"
            f"  Added: {sorted(added)[:10]}\n"
            f"  Removed: {sorted(removed)[:10]}"
        )

    @pytest.mark.skip(
        reason="CI ghost drift: passes locally, fails in CI due to env-dependent schema loading. CAB-2055 follow-up."
    )
    def test_openapi_schemas_match_snapshot(self):
        """Schema names must match committed snapshot (catches added/removed models)."""
        with open(SNAPSHOT_PATH) as f:
            snapshot = json.load(f)

        live = self._get_live_schema()

        snapshot_schemas = set(snapshot.get("components", {}).get("schemas", {}).keys())
        live_schemas = set(live.get("components", {}).get("schemas", {}).keys())

        added = live_schemas - snapshot_schemas
        removed = snapshot_schemas - live_schemas

        assert not added and not removed, (
            f"Schema names changed. Update the snapshot.\n"
            f"  Added: {sorted(added)[:10]}\n"
            f"  Removed: {sorted(removed)[:10]}"
        )

    # Pydantic internal schemas that vary across versions (e.g. 2.5 vs 2.12)
    PYDANTIC_INTERNAL_SCHEMAS = {"ValidationError", "HTTPValidationError"}

    def test_openapi_schema_properties_match_snapshot(self):
        """Schema property names must match snapshot (catches added/removed fields)."""
        with open(SNAPSHOT_PATH) as f:
            snapshot = json.load(f)

        live = self._get_live_schema()

        snapshot_schemas = snapshot.get("components", {}).get("schemas", {})
        live_schemas = live.get("components", {}).get("schemas", {})

        diffs = []
        for name in sorted(set(snapshot_schemas) & set(live_schemas)):
            if name in self.PYDANTIC_INTERNAL_SCHEMAS:
                continue
            snap_props = set(snapshot_schemas[name].get("properties", {}).keys())
            live_props = set(live_schemas[name].get("properties", {}).keys())
            added = live_props - snap_props
            removed = snap_props - live_props
            if added or removed:
                diffs.append(f"  {name}: +{sorted(added)} -{sorted(removed)}")

        assert not diffs, "Schema properties changed. Update the snapshot.\n" + "\n".join(diffs[:10])

    def test_openapi_schema_has_required_paths(self):
        """Key API endpoints must be present in the schema."""
        live = self._get_live_schema()
        paths = live.get("paths", {})

        for path in REQUIRED_PATHS:
            matching = [p for p in paths if p.startswith(path)]
            assert matching, f"Required path prefix '{path}' not found in OpenAPI schema"

    def test_openapi_schema_version(self):
        """OpenAPI version must match settings.VERSION."""
        live = self._get_live_schema()
        assert live["info"]["version"] == settings.VERSION

    def test_openapi_schema_has_core_schemas(self):
        """Core response schemas must exist (CAB-1671: expanded list)."""
        live = self._get_live_schema()
        schemas = live.get("components", {}).get("schemas", {})

        for schema_name in REQUIRED_SCHEMAS:
            assert schema_name in schemas, f"Core schema '{schema_name}' not found in OpenAPI"

    def test_openapi_schema_required_fields(self):
        """Required fields per schema must exist — catches silent field removals (CAB-1671)."""
        live = self._get_live_schema()
        schemas = live.get("components", {}).get("schemas", {})

        for schema_name, required_fields in REQUIRED_FIELDS.items():
            assert schema_name in schemas, f"Schema '{schema_name}' not found"
            props = set(schemas[schema_name].get("properties", {}).keys())
            for field in required_fields:
                assert field in props, (
                    f"Required field '{field}' missing from schema '{schema_name}'. " f"Available: {sorted(props)[:15]}"
                )

    def test_openapi_schema_field_types_stable(self):
        """Field types must not change silently — catches type regressions (CAB-1671)."""
        with open(SNAPSHOT_PATH) as f:
            snapshot = json.load(f)

        live = self._get_live_schema()

        snapshot_schemas = snapshot.get("components", {}).get("schemas", {})
        live_schemas = live.get("components", {}).get("schemas", {})

        type_diffs = []
        for name in sorted(set(snapshot_schemas) & set(live_schemas)):
            if name in self.PYDANTIC_INTERNAL_SCHEMAS:
                continue
            snap_props = snapshot_schemas[name].get("properties", {})
            live_props = live_schemas[name].get("properties", {})
            for prop_name in sorted(set(snap_props) & set(live_props)):
                snap_type = snap_props[prop_name].get("type")
                live_type = live_props[prop_name].get("type")
                if snap_type and live_type and snap_type != live_type:
                    type_diffs.append(f"  {name}.{prop_name}: {snap_type} -> {live_type}")

        assert not type_diffs, "Schema field types changed. Update the snapshot.\n" + "\n".join(type_diffs[:10])

    def test_openapi_methods_stable(self):
        """HTTP methods per path must not change silently (CAB-1671)."""
        with open(SNAPSHOT_PATH) as f:
            snapshot = json.load(f)

        live = self._get_live_schema()

        snapshot_paths = snapshot.get("paths", {})
        live_paths = live.get("paths", {})

        method_diffs = []
        for path in sorted(set(snapshot_paths) & set(live_paths)):
            snap_methods = set(snapshot_paths[path].keys())
            live_methods = set(live_paths[path].keys())
            added = live_methods - snap_methods
            removed = snap_methods - live_methods
            if added or removed:
                method_diffs.append(f"  {path}: +{sorted(added)} -{sorted(removed)}")

        assert not method_diffs, "HTTP methods changed on existing paths. Update the snapshot.\n" + "\n".join(
            method_diffs[:10]
        )


class TestCAB2159BackendGaps:
    """Regression guards for CAB-2159 — OpenAPI contract gaps blocking UI-1-Wave2.

    See ``control-plane-ui/rewrite-bugs.md`` for the original discovery notes.
    """

    def _get_schemas(self) -> dict:
        return app.openapi().get("components", {}).get("schemas", {})

    # ---------------------------------------------------------------------
    # BUG-1 — ApplicationResponse must be the canonical schema name
    # ---------------------------------------------------------------------

    def test_bug1_application_response_is_canonical(self):
        """Portal ``ApplicationResponse`` must collapse to an un-namespaced schema.

        Namespaced ``src__routers__portal_applications__ApplicationResponse`` forces
        the UI to spell the namespace in consumer code. Admin variant is renamed
        to ``AdminApplicationResponse`` so only one class owns the short name.
        """
        schemas = self._get_schemas()
        assert (
            "ApplicationResponse" in schemas
        ), "ApplicationResponse missing — portal class must own the canonical name"
        assert "AdminApplicationResponse" in schemas, (
            "AdminApplicationResponse missing — admin router class must be renamed "
            "to free the canonical name for portal"
        )
        # Namespaced aliases must NOT leak — they are the symptom of the collision
        namespaced = [k for k in schemas if k.startswith("src__routers__") and "ApplicationResponse" in k]
        assert not namespaced, (
            f"Namespaced ApplicationResponse variants still present: {namespaced}. "
            "Both class names must be distinct."
        )

    # ---------------------------------------------------------------------
    # BUG-2 — GatewayInstanceResponse must expose ``source`` + Literal enums
    # ---------------------------------------------------------------------

    def test_bug2_gateway_instance_response_source_field(self):
        """``source`` column exists on the ORM model — must be in the response schema."""
        gir = self._get_schemas().get("GatewayInstanceResponse", {})
        props = gir.get("properties", {})
        assert "source" in props, (
            "GatewayInstanceResponse.source missing — ORM has it (CAB-1979), "
            "response schema must expose it so UI can branch on argocd vs self_register"
        )

    def test_bug2_gateway_instance_response_enum_fields(self):
        """``gateway_type``, ``mode``, ``status`` must be ``enum`` not plain string."""
        gir = self._get_schemas().get("GatewayInstanceResponse", {})
        props = gir.get("properties", {})

        def _has_enum(prop: dict) -> bool:
            if "enum" in prop:
                return True
            return any("enum" in sub for sub in prop.get("anyOf", []))

        for field in ("gateway_type", "mode", "status", "source"):
            assert _has_enum(props.get(field, {})), (
                f"GatewayInstanceResponse.{field} must be Literal[...] not plain str. " f"Current: {props.get(field)}"
            )

    # ---------------------------------------------------------------------
    # BUG-4 — APIResponse must expose ``created_at``/``updated_at``/``audience``
    # ---------------------------------------------------------------------

    def test_bug4_api_response_timestamps_and_audience(self):
        """APIResponse must carry the same timestamp + audience contract as siblings."""
        ar = self._get_schemas().get("APIResponse", {})
        props = ar.get("properties", {})
        for field in ("created_at", "updated_at", "audience"):
            assert field in props, (
                f"APIResponse.{field} missing — UI consumes all three " f"(see control-plane-ui/rewrite-bugs.md BUG-4)"
            )

    def test_bug4_api_response_audience_is_enum(self):
        """``audience`` must narrow to ``public|internal|partner``."""
        ar = self._get_schemas().get("APIResponse", {})
        audience = ar.get("properties", {}).get("audience", {})
        values = set(audience.get("enum") or [])
        if not values:
            for sub in audience.get("anyOf", []):
                values |= set(sub.get("enum") or [])
        assert values == {
            "public",
            "internal",
            "partner",
        }, f"APIResponse.audience must be Literal['public','internal','partner']. Got: {values}"
