"""
OpenAPI Contract Tests — structural validation for API schema stability.

Ensures the OpenAPI schema generated by FastAPI matches the committed snapshot
at a structural level (paths, schemas, properties, methods). Tolerant of
Pydantic version differences (allOf/$ref, additionalProperties, title).

When the API changes intentionally, update the snapshot:

    cd control-plane-api && python -c "
    import os, json
    os.environ['ENABLE_DEPLOYMENT_WORKER'] = 'false'
    os.environ['ENABLE_SNAPSHOT_CONSUMER'] = 'false'
    from src.main import app
    with open('openapi-snapshot.json', 'w') as f:
        json.dump(app.openapi(), f, indent=2, sort_keys=True, default=str)
    "
"""
import json
from pathlib import Path

from src.config import settings
from src.main import app

SNAPSHOT_PATH = Path(__file__).parent.parent / "openapi-snapshot.json"

REQUIRED_PATHS = [
    "/v1/tenants",
    "/v1/subscriptions",
    "/v1/admin/gateways",
    "/v1/mcp/servers",
    "/health",
]


class TestOpenAPIContract:
    def _get_live_schema(self) -> dict:
        schema = app.openapi()
        return json.loads(json.dumps(schema, sort_keys=True, default=str))

    def test_openapi_paths_match_snapshot(self):
        """API paths must match committed snapshot (catches added/removed endpoints)."""
        assert SNAPSHOT_PATH.exists(), (
            f"OpenAPI snapshot not found at {SNAPSHOT_PATH}. "
            "Run the snapshot generation command in the module docstring."
        )

        with open(SNAPSHOT_PATH) as f:
            snapshot = json.load(f)

        live = self._get_live_schema()

        snapshot_paths = set(snapshot.get("paths", {}).keys())
        live_paths = set(live.get("paths", {}).keys())

        added = live_paths - snapshot_paths
        removed = snapshot_paths - live_paths

        assert not added and not removed, (
            f"API paths changed. Update the snapshot.\n"
            f"  Added: {sorted(added)[:10]}\n"
            f"  Removed: {sorted(removed)[:10]}"
        )

    def test_openapi_schemas_match_snapshot(self):
        """Schema names must match committed snapshot (catches added/removed models)."""
        with open(SNAPSHOT_PATH) as f:
            snapshot = json.load(f)

        live = self._get_live_schema()

        snapshot_schemas = set(snapshot.get("components", {}).get("schemas", {}).keys())
        live_schemas = set(live.get("components", {}).get("schemas", {}).keys())

        added = live_schemas - snapshot_schemas
        removed = snapshot_schemas - live_schemas

        assert not added and not removed, (
            f"Schema names changed. Update the snapshot.\n"
            f"  Added: {sorted(added)[:10]}\n"
            f"  Removed: {sorted(removed)[:10]}"
        )

    # Pydantic internal schemas that vary across versions (e.g. 2.5 vs 2.12)
    PYDANTIC_INTERNAL_SCHEMAS = {"ValidationError", "HTTPValidationError"}

    def test_openapi_schema_properties_match_snapshot(self):
        """Schema property names must match snapshot (catches added/removed fields)."""
        with open(SNAPSHOT_PATH) as f:
            snapshot = json.load(f)

        live = self._get_live_schema()

        snapshot_schemas = snapshot.get("components", {}).get("schemas", {})
        live_schemas = live.get("components", {}).get("schemas", {})

        diffs = []
        for name in sorted(set(snapshot_schemas) & set(live_schemas)):
            if name in self.PYDANTIC_INTERNAL_SCHEMAS:
                continue
            snap_props = set(snapshot_schemas[name].get("properties", {}).keys())
            live_props = set(live_schemas[name].get("properties", {}).keys())
            added = live_props - snap_props
            removed = snap_props - live_props
            if added or removed:
                diffs.append(f"  {name}: +{sorted(added)} -{sorted(removed)}")

        assert not diffs, (
            f"Schema properties changed. Update the snapshot.\n" + "\n".join(diffs[:10])
        )

    def test_openapi_schema_has_required_paths(self):
        """Key API endpoints must be present in the schema."""
        live = self._get_live_schema()
        paths = live.get("paths", {})

        for path in REQUIRED_PATHS:
            matching = [p for p in paths if p.startswith(path)]
            assert matching, f"Required path prefix '{path}' not found in OpenAPI schema"

    def test_openapi_schema_version(self):
        """OpenAPI version must match settings.VERSION."""
        live = self._get_live_schema()
        assert live["info"]["version"] == settings.VERSION

    def test_openapi_schema_has_core_schemas(self):
        """Core response schemas must exist."""
        live = self._get_live_schema()
        schemas = live.get("components", {}).get("schemas", {})

        core_schemas = [
            "TenantResponse",
            "SubscriptionResponse",
            "ContractResponse",
            "GatewayInstanceResponse",
            "MCPServerResponse",
            "PlatformStatusResponse",
        ]

        for schema_name in core_schemas:
            assert schema_name in schemas, f"Core schema '{schema_name}' not found in OpenAPI"
