apiVersion: stoa.io/v1
kind: WebMethodsPolicy
metadata:
  name: jwt-validation
  description: "JWT token validation via OIDC provider (e.g., Keycloak)"

spec:
  type: jwt-validation
  config:
    # OIDC Discovery endpoint
    issuer: "${OIDC_ISSUER_URL}"

    # JWKS endpoint for signature validation
    jwksUri: "${OIDC_ISSUER_URL}/protocol/openid-connect/certs"

    # Accepted audiences
    audiences:
      - ${OAUTH_AUDIENCE_API}
      - ${OAUTH_AUDIENCE_PORTAL}

    # Accepted algorithms
    algorithms:
      - RS256
      - RS384
      - RS512

    # Required claims
    requiredClaims:
      - sub
      - iat
      - exp

    # Token extraction
    tokenLocation: header
    tokenHeader: Authorization
    tokenPrefix: "Bearer "

    # JWKS cache (performance)
    jwksCacheTtl: 3600s

    # Claims propagation to backend
    propagateClaims:
      - sub
      - email
      - preferred_username
      - realm_access

    # Headers added to backend requests
    forwardHeaders:
      X-User-Id: "${claims.sub}"
      X-User-Email: "${claims.email}"
      X-User-Roles: "${claims.realm_access.roles}"
