#!/usr/bin/env python3
"""
STOA Platform — mTLS Demo Seed Script (CAB-864).

!! DEMO ONLY — NOT FOR PRODUCTION USE !!
Credentials generated by this script are for demo/testing purposes only.
Never use demo credentials in production environments.

Bulk-onboards 100 consumers with X.509 client certificates for the mTLS demo.
Certificates must be pre-generated with generate-mtls-certs.sh.

Usage:
    # Generate certs first
    ./scripts/demo/generate-mtls-certs.sh

    # Then seed consumers
    python3 scripts/demo/seed-mtls-demo.py

    # Custom settings
    CONTROL_PLANE_URL=https://api.gostoa.dev \
    KEYCLOAK_URL=https://auth.gostoa.dev \
    MTLS_TENANT=acme-corp \
    python3 scripts/demo/seed-mtls-demo.py

    # Force re-seed (overwrite existing credentials)
    python3 scripts/demo/seed-mtls-demo.py --force

Output:
    scripts/demo/certs/credentials.json — client_id + client_secret for each consumer
"""

import argparse
import csv
import io
import json
import os
import sys
from pathlib import Path

try:
    import httpx
except ImportError:
    print("Error: httpx not installed. Run: pip install httpx")
    sys.exit(1)

# Configuration
API_URL = os.getenv("CONTROL_PLANE_URL", "http://localhost:8000")
KEYCLOAK_URL = os.getenv("KEYCLOAK_URL", "http://localhost:8080")
KEYCLOAK_REALM = os.getenv("KEYCLOAK_REALM", "stoa")
ADMIN_USERNAME = os.getenv("ADMIN_USERNAME", "admin")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "")
MTLS_TENANT = os.getenv("MTLS_TENANT", "acme-corp")
CERTS_DIR = Path(os.getenv("MTLS_CERTS_DIR", Path(__file__).parent / "certs"))

# =============================================================================
# Auth
# =============================================================================


def get_admin_token() -> str | None:
    """Get admin access token from Keycloak master realm."""
    if not ADMIN_PASSWORD:
        print("  [!] ADMIN_PASSWORD not set, trying without auth...")
        return None

    try:
        resp = httpx.post(
            f"{KEYCLOAK_URL}/realms/master/protocol/openid-connect/token",
            data={
                "grant_type": "password",
                "client_id": "admin-cli",
                "username": ADMIN_USERNAME,
                "password": ADMIN_PASSWORD,
            },
            timeout=10.0,
        )
        if resp.status_code == 200:
            return resp.json().get("access_token")
        print(f"  [-] Failed to get admin token: {resp.status_code}")
        return None
    except Exception as e:
        print(f"  [-] Could not connect to Keycloak: {e}")
        return None


# =============================================================================
# Bulk onboarding
# =============================================================================


def build_bulk_csv(cert_files: list[Path]) -> bytes:
    """Build a CSV for the bulk consumer endpoint with certificate PEMs."""
    output = io.StringIO()
    writer = csv.writer(output, quoting=csv.QUOTE_ALL)
    writer.writerow(["external_id", "name", "email", "company", "certificate_pem"])

    for cert_path in cert_files:
        # Extract number from filename: client-001.pem → 001
        num = cert_path.stem.replace("client-", "")
        external_id = f"api-consumer-{num}"
        name = f"API Consumer {num}"
        email = f"consumer-{num}@acme-demo.test"
        company = "Acme Corp"

        pem_data = cert_path.read_text().strip()
        writer.writerow([external_id, name, email, company, pem_data])

    return output.getvalue().encode("utf-8")


def seed_consumers(token: str | None) -> dict:
    """Bulk-upload consumers with certificates."""
    # Find all client cert files
    cert_files = sorted(CERTS_DIR.glob("client-*.pem"))
    # Filter out key files
    cert_files = [f for f in cert_files if "-key" not in f.name]

    if not cert_files:
        print(f"  [-] No client certificates found in {CERTS_DIR}/")
        print("      Run ./scripts/demo/generate-mtls-certs.sh first")
        sys.exit(1)

    print(f"  [*] Found {len(cert_files)} client certificates")

    # Build CSV
    csv_data = build_bulk_csv(cert_files)

    # Upload via bulk endpoint
    headers = {}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    url = f"{API_URL}/v1/consumers/{MTLS_TENANT}/bulk"
    print(f"  [*] Uploading to {url}...")

    try:
        resp = httpx.post(
            url,
            headers=headers,
            files={"file": ("consumers.csv", csv_data, "text/csv")},
            timeout=60.0,
        )

        if resp.status_code in (200, 201):
            result = resp.json()
            return result
        else:
            print(f"  [-] Bulk upload failed: {resp.status_code}")
            print(f"      {resp.text[:500]}")
            return {"total": len(cert_files), "success": 0, "failed": len(cert_files), "results": []}
    except Exception as e:
        print(f"  [-] Error during bulk upload: {e}")
        return {"total": len(cert_files), "success": 0, "failed": len(cert_files), "results": []}


# =============================================================================
# Mixed profile post-processing
# =============================================================================


REVOKE_EXTERNAL_IDS = ["api-consumer-099", "api-consumer-100"]


def apply_mixed_profile(token: str | None, result: dict) -> dict:
    """Post-process bulk creation: revoke 2 consumers for mixed status demo."""
    revoked = 0
    for item in result.get("results", []):
        ext_id = item.get("external_id", "")
        consumer_id = item.get("consumer_id", "")
        if ext_id in REVOKE_EXTERNAL_IDS and consumer_id:
            ok = revoke_consumer_certificate(token, consumer_id)
            if ok:
                revoked += 1
                item["certificate_status"] = "revoked"
                print(f"    [+] Revoked: {ext_id} ({consumer_id})")
            else:
                print(f"    [-] Failed to revoke: {ext_id}")

    print(f"  [*] Mixed profile: {revoked}/{len(REVOKE_EXTERNAL_IDS)} consumers revoked")
    return result


def revoke_consumer_certificate(token: str | None, consumer_id: str) -> bool:
    """Revoke a consumer's certificate via CP API."""
    headers = {}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    url = f"{API_URL}/v1/consumers/{MTLS_TENANT}/{consumer_id}/certificate/revoke"
    try:
        resp = httpx.post(url, headers=headers, timeout=10.0)
        return resp.status_code == 200
    except Exception as e:
        print(f"    [-] Revoke error: {e}")
        return False


def save_credentials(result: dict) -> None:
    """Save client_id + client_secret pairs for demo use."""
    credentials = []
    for item in result.get("results", []):
        if item.get("status") == "created" and item.get("client_id"):
            credentials.append({
                "external_id": item.get("external_id", ""),
                "consumer_id": item.get("consumer_id", ""),
                "client_id": item.get("client_id", ""),
                "client_secret": item.get("client_secret", ""),
            })

    creds_path = CERTS_DIR / "credentials.json"
    output = {
        "_warning": "DEMO ONLY — NOT FOR PRODUCTION USE. These credentials are for demo/testing purposes only.",
        "credentials": credentials,
    }
    creds_path.write_text(json.dumps(output, indent=2))
    print(f"  [+] Saved {len(credentials)} credentials to {creds_path}")


# =============================================================================
# Verification
# =============================================================================


def verify_consumers(token: str | None) -> int:
    """Verify consumers are visible via the API. Returns count or -1 on error."""
    headers = {}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    try:
        resp = httpx.get(
            f"{API_URL}/v1/consumers/{MTLS_TENANT}",
            headers=headers,
            params={"page_size": 1},
            timeout=10.0,
        )
        if resp.status_code == 200:
            return resp.json().get("total", 0)
        return -1
    except Exception:
        return -1


def verify_fingerprints() -> int:
    """Verify fingerprints.csv has expected entries. Returns count."""
    fp_path = CERTS_DIR / "fingerprints.csv"
    if not fp_path.exists():
        return 0
    lines = fp_path.read_text().strip().splitlines()
    return max(0, len(lines) - 1)  # minus header


def print_verification_summary(
    token: str | None,
    total: int,
    success: int,
    failed: int,
    credentials: list[dict],
) -> None:
    """Print verification results and next steps (pattern from seed-demo-data.py)."""
    print()
    print("=" * 60)
    print("  VERIFICATION")
    print("=" * 60)

    # Check API visibility
    api_count = verify_consumers(token)
    fp_count = verify_fingerprints()
    creds_count = len(credentials)

    checks = [
        ("Bulk upload", success > 0, f"{success}/{total} consumers created"),
        ("Credentials saved", creds_count > 0, f"{creds_count} in credentials.json"),
        ("Fingerprints CSV", fp_count > 0, f"{fp_count} entries"),
        (
            "API visibility",
            api_count > 0,
            f"{api_count} consumers via GET /v1/consumers/{MTLS_TENANT}"
            if api_count >= 0
            else "API not reachable (offline mode?)",
        ),
    ]

    all_ok = True
    for name, ok, detail in checks:
        status = "[OK]" if ok else "[--]"
        if not ok:
            all_ok = False
        print(f"  {status} {name}: {detail}")

    # Demo credentials (first 3)
    if credentials:
        print()
        print("  Demo Credentials (first 3):")
        print("  " + "-" * 56)
        for c in credentials[:3]:
            print(f"    {c['external_id']}")
            print(f"      client_id:     {c.get('client_id', 'N/A')}")
            print(f"      client_secret:  {c.get('client_secret', 'N/A')[:20]}...")

    # Verification commands
    print()
    print("  Verify manually:")
    print("  " + "-" * 56)
    print(f"    # List consumers (API)")
    print(f"    curl -s {API_URL}/v1/consumers/{MTLS_TENANT}?page_size=5 \\")
    print(f"      -H \"Authorization: Bearer $ADMIN_TOKEN\" | python3 -m json.tool")
    print()
    print(f"    # Check fingerprints")
    print(f"    head -5 {CERTS_DIR}/fingerprints.csv")
    print()
    print(f"    # Verify cert chain")
    print(f"    openssl verify -CAfile {CERTS_DIR}/stoa-demo-ca.pem {CERTS_DIR}/client-001.pem")

    # Next steps
    print()
    print("  Next steps:")
    print("  " + "-" * 56)
    print("    1. source scripts/demo/mtls-demo-commands.sh   # Load demo variables")
    print("    2. Run STEP 1-6 during the demo                # Copy-paste curl commands")
    print()
    print("  Console UI:")
    print("  " + "-" * 56)
    print(f"    NOTE: No consumer list page in Console UI yet.")
    print(f"    Consumers are visible via API only (curl or Postman).")
    print(f"    The Portal has CertificateUploader component (not wired to listing).")

    print()
    print("=" * 60)
    if all_ok:
        print(f"  READY: {success} consumers with mTLS certificates")
    elif success > 0:
        print(f"  PARTIAL: {success} ok, {failed} failed — check logs above")
    else:
        print(f"  FAILED: No consumers created — check API connectivity")
    print("=" * 60)


# =============================================================================
# Main
# =============================================================================


def main() -> None:
    parser = argparse.ArgumentParser(description="STOA mTLS Demo Seed (CAB-864)")
    parser.add_argument("--force", action="store_true", help="Overwrite existing credentials")
    parser.add_argument(
        "--profile",
        choices=["default", "mixed"],
        default="default",
        help="Seed profile: 'mixed' revokes consumers 099-100 for demo edge cases",
    )
    args = parser.parse_args()

    creds_path = CERTS_DIR / "credentials.json"

    print("=" * 60)
    print("  STOA mTLS Demo Seed (CAB-864)")
    print("=" * 60)
    print(f"  API:     {API_URL}")
    print(f"  KC:      {KEYCLOAK_URL}")
    print(f"  Tenant:  {MTLS_TENANT}")
    print(f"  Certs:   {CERTS_DIR}")
    print(f"  Profile: {args.profile}")
    print()

    # Check certs exist
    if not CERTS_DIR.exists():
        print(f"  [-] Certs directory not found: {CERTS_DIR}")
        print("      Run: ./scripts/demo/generate-mtls-certs.sh")
        sys.exit(1)

    # Check if already seeded
    if creds_path.exists() and not args.force:
        data = json.loads(creds_path.read_text())
        creds = data.get("credentials", data) if isinstance(data, dict) else data
        count = len(creds)
        print(f"  [!] Already seeded ({count} credentials in {creds_path})")
        print("      Use --force to re-seed")
        sys.exit(0)

    # Get auth token
    print("[1/4] Authenticating...")
    token = get_admin_token()
    if token:
        print("  [+] Admin token acquired")
    else:
        print("  [!] Proceeding without auth (may fail on protected endpoints)")

    # Bulk onboard
    print("[2/4] Bulk onboarding consumers with certificates...")
    result = seed_consumers(token)

    total = result.get("total", 0)
    success = result.get("success", 0)
    failed = result.get("failed", 0)

    print(f"\n  Result: {success}/{total} consumers created ({failed} failed)")

    # Mixed profile post-processing (revoke 2 consumers)
    if args.profile == "mixed" and success > 0:
        print("[2b/4] Applying mixed profile (revoking 2 consumers)...")
        result = apply_mixed_profile(token, result)

    # Save credentials
    print("[3/4] Saving credentials...")
    save_credentials(result)

    # Load saved credentials for verification summary
    creds_path_final = CERTS_DIR / "credentials.json"
    saved_creds = []
    if creds_path_final.exists():
        data = json.loads(creds_path_final.read_text())
        saved_creds = data.get("credentials", data) if isinstance(data, dict) else data

    # Verification + next steps
    print("[4/4] Verifying...")
    print_verification_summary(token, total, success, failed, saved_creds)


if __name__ == "__main__":
    main()
