{{- if and .Values.podDisruptionBudget .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stoa-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: stoa-gateway
    app.kubernetes.io/component: gateway
    {{- include "stoa-platform.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: stoa-gateway
{{- end }}
