# HTTPRoute for opensearch namespace
# SnippetsFilter increases proxy buffers for OSD OIDC headers
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: opensearch-dashboards
  namespace: opensearch
spec:
  parentRefs:
    - name: stoa
      namespace: nginx-gateway
  hostnames:
    - opensearch.gostoa.dev
  rules:
    - backendRefs:
        - name: opensearch-dashboards
          port: 5601
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.nginx.org
            kind: SnippetsFilter
            name: osd-proxy-buffers
