apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-staging
resources:
  - ../../base
  - ingress.yaml
patches:
  - target:
      kind: Deployment
      name: stoa-gateway
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_ENVIRONMENT
          value: "staging"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_INSTANCE_NAME
          value: "stoa-gateway-staging"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_GATEWAY_EXTERNAL_URL
          value: "https://staging-gw-k3s.gostoa.dev"
  - target:
      kind: Deployment
      name: stoa-link-wm
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_ENVIRONMENT
          value: "staging"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_INSTANCE_NAME
          value: "stoa-link-wm-staging"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STOA_GATEWAY_EXTERNAL_URL
          value: "https://staging-wm-k3s.gostoa.dev"
