#!/usr/bin/env bash
# generate-cli-context.sh — Generates .claude/context/cli-reference.md
# from stoactl --help output + JSON Schema registry.
#
# Usage: scripts/generate-cli-context.sh [--stoactl PATH]
#
# Phase 5 of CAB-2053: CLI-first context pack for Claude sessions.
# Goal: replace src/ scanning with a compact CLI + schema reference.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STOACTL="${REPO_ROOT}/stoa-go/bin/stoactl"
SCHEMAS_DIR="${REPO_ROOT}/charts/stoa-platform/schemas"
OUTPUT="${REPO_ROOT}/.claude/context/cli-reference.md"

# Parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    --stoactl) STOACTL="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# Build stoactl if needed
if [[ ! -x "$STOACTL" ]]; then
  echo "Building stoactl..." >&2
  (cd "${REPO_ROOT}/stoa-go" && go build -o bin/stoactl ./cmd/stoactl/) || {
    echo "ERROR: Failed to build stoactl" >&2; exit 1
  }
fi

mkdir -p "$(dirname "$OUTPUT")"

# --- Generate the reference ---

cat > "$OUTPUT" << 'HEADER'
# STOA CLI-First Reference

> Auto-generated by `scripts/generate-cli-context.sh`. Do not edit manually.
> Regenerate after any stoactl command or schema change.
>
> **Purpose**: This file provides the complete STOA API surface via stoactl commands
> and JSON Schemas. Use this instead of reading `control-plane-api/src/` when you
> need to understand what resources exist and how to manipulate them.

## Quick Decision Tree

```
Need to know what resources exist?     → "Resource Kinds" section below
Need to create/update a resource?      → stoactl apply -f <yaml>
Need to list resources?                → stoactl get <resource>
Need to delete a resource?             → stoactl delete <kind> <id>
Need resource field details?           → "Resource Schemas" section below
Need to check system health?           → stoactl doctor
Need API endpoint for code?            → "Endpoint Map" section below
```

HEADER

# --- Commands section ---
echo "## Commands" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo '```' >> "$OUTPUT"

# Capture root help
"$STOACTL" --help 2>&1 | sed '/^$/d' >> "$OUTPUT"

echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Subcommand help for key commands
for cmd in get apply delete catalog audit gateway mcp bridge auth; do
  echo "### stoactl $cmd" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  "$STOACTL" "$cmd" --help 2>&1 | sed '/^$/d' >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  echo "" >> "$OUTPUT"
done

# --- Resource Schemas section ---
echo "## Resource Schemas (gostoa.dev/v1beta1)" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "All resources follow the Kubernetes-style structure:" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat >> "$OUTPUT" << 'STRUCTURE'
```yaml
apiVersion: gostoa.dev/v1beta1
kind: <Kind>
metadata:
  name: <unique-name>
  namespace: <tenant-id>  # optional
  labels: {}              # optional key-value pairs
spec:
  # kind-specific fields below
```

STRUCTURE

# Extract compact spec from each schema
for schema_file in "$SCHEMAS_DIR"/*.schema.json; do
  [[ -f "$schema_file" ]] || continue
  python3 -c "
import json, sys

with open('$schema_file') as f:
    s = json.load(f)

kind = s['properties']['kind']['const']
spec = s['properties']['spec']
required = set(spec.get('required', []))
props = spec.get('properties', {})
defs = spec.get('\$defs', {})

print(f'### {kind}')
print()
print('\`\`\`yaml')
print(f'kind: {kind}')
print('spec:')

for name, prop in props.items():
    # Resolve type
    if '\$ref' in prop:
        ref_name = prop['\$ref'].split('/')[-1]
        if ref_name in defs:
            enum_vals = defs[ref_name].get('enum', [])
            typ = ' | '.join(enum_vals) if enum_vals else ref_name
        else:
            typ = ref_name
    elif 'anyOf' in prop:
        types = [t.get('type', '?') for t in prop['anyOf'] if t.get('type') != 'null']
        typ = types[0] if types else 'any'
    else:
        typ = prop.get('type', 'object')

    req_marker = '  # required' if name in required else ''
    default = prop.get('default')
    default_str = f'  # default: {default}' if default is not None and name not in required else ''

    print(f'  {name}: {typ}{req_marker}{default_str}')

print('\`\`\`')
print()
" >> "$OUTPUT"
done

# --- Endpoint Map section ---
cat >> "$OUTPUT" << 'ENDPOINTS'
## Endpoint Map (stoactl command -> CP API)

| stoactl command | HTTP Method | CP API Endpoint |
|-----------------|-------------|-----------------|
| `get apis` | GET | `/v1/tenants/{t}/apis` |
| `get tenants` | GET | `/v1/tenants` |
| `get gateways` | GET | `/v1/gateways` |
| `get subscriptions` | GET | `/v1/subscriptions/{t}` |
| `get consumers` | GET | `/v1/consumers/{t}` |
| `get contracts` | GET | `/v1/tenants/{t}/contracts` |
| `get service-accounts` | GET | `/v1/service-accounts` |
| `get environments` | GET | `/v1/environments` |
| `get plans` | GET | `/v1/plans/{t}` |
| `get webhooks` | GET | `/v1/tenants/{t}/webhooks` |
| `apply -f` (API) | POST | `/v1/tenants/{t}/apis` |
| `apply -f` (Tenant) | POST | `/v1/tenants` |
| `apply -f` (Gateway) | POST | `/v1/gateways` |
| `apply -f` (Subscription) | POST | `/v1/subscriptions` |
| `apply -f` (Consumer) | POST | `/v1/consumers/{t}` |
| `apply -f` (Contract) | POST | `/v1/tenants/{t}/contracts` |
| `apply -f` (MCPServer) | POST | `/v1/mcp-servers` |
| `apply -f` (ServiceAccount) | POST | `/v1/service-accounts` |
| `apply -f` (Plan) | POST | `/v1/plans/{t}` |
| `apply -f` (Webhook) | POST | `/v1/tenants/{t}/webhooks` |
| `delete <kind> <id>` | DELETE | `/v1/<resource>/{id}` |
| `catalog sync --dry-run` | GET | `/v1/admin/catalog/drift` |
| `catalog sync --apply` | POST | `/v1/admin/catalog/sync` |
| `audit export` | GET | `/v1/audit` |
| `gateway health` | GET | `/health` (gateway direct) |
| `mcp list-tools` | GET | `/mcp/tools/list` |
| `mcp list-servers` | GET | `/v1/mcp-servers` |
| `mcp call` | POST | `/mcp/tools/call` |
| `bridge` | N/A | Local OpenAPI→CRD conversion |
| `doctor` | GET | Multiple health endpoints |
| `auth status` | GET | `/v1/auth/me` |

## Gateway Types (enum)

`webmethods`, `kong`, `apigee`, `aws_apigateway`, `azure_apim`, `gravitee`,
`stoa`, `stoa_edge_mcp`, `stoa_sidecar`, `stoa_proxy`, `stoa_shadow`

## Auth Types (API backend)

`none`, `api_key`, `bearer`, `basic`, `oauth2_cc`

## MCP Server Categories (enum)

`platform`, `tenant`, `public`

## MCP Server Visibility

Complex object: `{ roles: string[] | null, exclude_roles: string[] | null, public: boolean }`
ENDPOINTS

# --- Footer ---
GENERATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
SCHEMA_COUNT=$(ls "$SCHEMAS_DIR"/*.schema.json 2>/dev/null | wc -l | tr -d ' ')

cat >> "$OUTPUT" << EOF

---
*Generated: ${GENERATED_AT} | Schemas: ${SCHEMA_COUNT} kinds | apiVersion: gostoa.dev/v1beta1*
EOF

# Report
SIZE=$(wc -c < "$OUTPUT" | tr -d ' ')
echo "Generated ${OUTPUT} (${SIZE} bytes, ${SCHEMA_COUNT} resource schemas)" >&2
