apiVersion: v1
kind: Service
metadata:
  name: kong-gateway
spec:
  selector:
    app: kong-gateway
  ports:
    - port: 8000
      targetPort: 8000
      name: proxy
    - port: 8001
      targetPort: 8001
      name: admin
