apiVersion: stoa.io/v1
kind: WebMethodsPolicy
metadata:
  name: error-snapshot
  description: "Capture des erreurs (4xx/5xx) vers Kafka Bridge pour time-travel debugging (CAB-485)"

spec:
  type: custom-extension
  stage: response  # Exécuter après la réponse backend

  config:
    # Condition de déclenchement
    condition: "${response.statusCode >= 400}"

    # Endpoint du Kafka Bridge
    endpoint: "http://stoa-platform-kafka-bridge.stoa-system:8080/snapshots"
    method: POST
    timeout: 5s

    # Ne pas bloquer la réponse si l'envoi échoue
    async: true
    failSilently: true

    # Headers de la requête vers le bridge
    headers:
      Content-Type: "application/json"

    # Payload à envoyer (template avec variables webMethods)
    payload: |
      {
        "tenant_id": "${request.headers['X-Tenant-ID'] ?? 'unknown'}",
        "trigger": "${response.statusCode >= 500 ? '5xx' : '4xx'}",
        "request": {
          "method": "${request.method}",
          "path": "${request.path}",
          "headers": ${request.headers.toJson()},
          "body": ${request.body ?? 'null'},
          "query_params": ${request.queryParams.toJson()},
          "client_ip": "${request.clientIP}",
          "user_agent": "${request.headers['User-Agent'] ?? ''}"
        },
        "response": {
          "status": ${response.statusCode},
          "headers": ${response.headers.toJson()},
          "body": ${response.body ?? 'null'},
          "duration_ms": ${response.duration}
        },
        "routing": {
          "api_name": "${api.name}",
          "api_version": "${api.version}",
          "route": "${request.path}",
          "backend_url": "${backend.url ?? ''}"
        },
        "trace_id": "${request.headers['X-Trace-ID'] ?? request.headers['X-Request-ID'] ?? ''}"
      }

---
# Configuration globale - appliquer à toutes les APIs
apiVersion: stoa.io/v1
kind: WebMethodsPolicyBinding
metadata:
  name: error-snapshot-global
  description: "Appliquer error-snapshot à toutes les APIs"

spec:
  policy: error-snapshot
  scope: global
  # Optionnel: exclure certaines APIs
  exclude:
    - health-check-api
    - metrics-api
