# Jira MCP Server
# Atlassian Jira integration for project and issue management

apiVersion: gostoa.dev/v1
kind: MCPServer
metadata:
  name: jira
  tenant: _platform
  version: "1.0.0"
  labels:
    managed-by: gitops
    environment: prod

spec:
  displayName: Jira
  description: |
    Atlassian Jira integration for AI-powered project management.
    Search, create, and manage issues across Jira projects.
  icon: https://cdn.worldvectorlogo.com/logos/jira-1.svg
  category: public
  status: active
  documentationUrl: https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/

  visibility:
    public: true

  subscription:
    requiresApproval: true
    autoApproveRoles:
      - cpi-admin
    defaultPlan: free

  tools:
    - name: search-issues
      displayName: Search Issues
      description: Search for issues using JQL (Jira Query Language)
      endpoint: /rest/api/3/search
      method: POST
      enabled: true
      inputSchema:
        type: object
        properties:
          jql:
            type: string
            description: JQL query string (e.g., "project = PROJ AND status = Open")
          fields:
            type: array
            description: Fields to return
            items:
              type: string
            default:
              - summary
              - status
              - assignee
              - priority
          maxResults:
            type: integer
            description: Maximum number of results
            default: 50
          startAt:
            type: integer
            description: Starting index for pagination
            default: 0
        required:
          - jql
      timeout: 30s
      rateLimit:
        requestsPerMinute: 100

    - name: get-issue
      displayName: Get Issue
      description: Get detailed information about a specific issue
      endpoint: /rest/api/3/issue/{issue_key}
      method: GET
      enabled: true
      inputSchema:
        type: object
        properties:
          issue_key:
            type: string
            description: The issue key (e.g., "PROJ-123")
          expand:
            type: string
            description: Additional fields to expand
            default: "changelog,renderedFields"
        required:
          - issue_key
      timeout: 30s
      rateLimit:
        requestsPerMinute: 100

    - name: create-issue
      displayName: Create Issue
      description: Create a new Jira issue
      endpoint: /rest/api/3/issue
      method: POST
      enabled: true
      requiresApproval: false
      inputSchema:
        type: object
        properties:
          project_key:
            type: string
            description: The project key (e.g., "PROJ")
          summary:
            type: string
            description: Issue summary/title
          description:
            type: string
            description: Issue description (supports ADF format)
          issue_type:
            type: string
            description: Issue type (Bug, Story, Task, Epic)
            default: Task
          priority:
            type: string
            description: Priority level (Highest, High, Medium, Low, Lowest)
            default: Medium
          assignee:
            type: string
            description: Assignee account ID (optional)
          labels:
            type: array
            description: Labels to add
            items:
              type: string
        required:
          - project_key
          - summary
          - issue_type
      timeout: 60s
      rateLimit:
        requestsPerMinute: 30

    - name: update-issue
      displayName: Update Issue
      description: Update an existing Jira issue
      endpoint: /rest/api/3/issue/{issue_key}
      method: PUT
      enabled: true
      inputSchema:
        type: object
        properties:
          issue_key:
            type: string
            description: The issue key to update
          summary:
            type: string
            description: New summary (optional)
          description:
            type: string
            description: New description (optional)
          priority:
            type: string
            description: New priority (optional)
          assignee:
            type: string
            description: New assignee account ID (optional)
        required:
          - issue_key
      timeout: 60s
      rateLimit:
        requestsPerMinute: 30

    - name: transition-issue
      displayName: Transition Issue
      description: Change the status of an issue (e.g., To Do -> In Progress -> Done)
      endpoint: /rest/api/3/issue/{issue_key}/transitions
      method: POST
      enabled: true
      inputSchema:
        type: object
        properties:
          issue_key:
            type: string
            description: The issue key
          transition_name:
            type: string
            description: Target transition/status name
          comment:
            type: string
            description: Comment to add with the transition
        required:
          - issue_key
          - transition_name
      timeout: 30s
      rateLimit:
        requestsPerMinute: 30

    - name: add-comment
      displayName: Add Comment
      description: Add a comment to an issue
      endpoint: /rest/api/3/issue/{issue_key}/comment
      method: POST
      enabled: true
      inputSchema:
        type: object
        properties:
          issue_key:
            type: string
            description: The issue key
          body:
            type: string
            description: Comment text
        required:
          - issue_key
          - body
      timeout: 30s
      rateLimit:
        requestsPerMinute: 60

    - name: list-projects
      displayName: List Projects
      description: List all Jira projects the user has access to
      endpoint: /rest/api/3/project/search
      method: GET
      enabled: true
      inputSchema:
        type: object
        properties:
          maxResults:
            type: integer
            description: Maximum number of results
            default: 50
        required: []
      timeout: 30s
      rateLimit:
        requestsPerMinute: 30

  backend:
    baseUrl: ${JIRA_BASE_URL:https://your-domain.atlassian.net}
    auth:
      type: api-key
      secretRef: vault:secret/data/integrations/jira#api_token
    timeout: 30s
    retries: 3
